// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// constrMLE
NumericVector constrMLE(NumericVector theta, const NumericVector indexes, const NumericMatrix basisMatrix, const NumericVector first_term);
RcppExport SEXP _ddfs_constrMLE(SEXP thetaSEXP, SEXP indexesSEXP, SEXP basisMatrixSEXP, SEXP first_termSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type indexes(indexesSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type basisMatrix(basisMatrixSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type first_term(first_termSEXP);
    rcpp_result_gen = Rcpp::wrap(constrMLE(theta, indexes, basisMatrix, first_term));
    return rcpp_result_gen;
END_RCPP
}
// constrMLE_ef
NumericVector constrMLE_ef(NumericVector theta, const NumericVector indexes, const NumericMatrix basisMatrix, const NumericVector first_term);
RcppExport SEXP _ddfs_constrMLE_ef(SEXP thetaSEXP, SEXP indexesSEXP, SEXP basisMatrixSEXP, SEXP first_termSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type indexes(indexesSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type basisMatrix(basisMatrixSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type first_term(first_termSEXP);
    rcpp_result_gen = Rcpp::wrap(constrMLE_ef(theta, indexes, basisMatrix, first_term));
    return rcpp_result_gen;
END_RCPP
}
// constrMLE_arma
arma::rowvec constrMLE_arma(arma::vec theta, arma::uvec indexes, arma::mat basisMatrix, arma::vec first_term);
RcppExport SEXP _ddfs_constrMLE_arma(SEXP thetaSEXP, SEXP indexesSEXP, SEXP basisMatrixSEXP, SEXP first_termSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indexes(indexesSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type basisMatrix(basisMatrixSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type first_term(first_termSEXP);
    rcpp_result_gen = Rcpp::wrap(constrMLE_arma(theta, indexes, basisMatrix, first_term));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ddfs_constrMLE", (DL_FUNC) &_ddfs_constrMLE, 4},
    {"_ddfs_constrMLE_ef", (DL_FUNC) &_ddfs_constrMLE_ef, 4},
    {"_ddfs_constrMLE_arma", (DL_FUNC) &_ddfs_constrMLE_arma, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_ddfs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
