# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

constrMLE <- function(theta, indexes, basisMatrix, first_term) {
    .Call(`_ddfs_constrMLE`, theta, indexes, basisMatrix, first_term)
}

constrMLE_ef <- function(theta, indexes, basisMatrix, first_term) {
    .Call(`_ddfs_constrMLE_ef`, theta, indexes, basisMatrix, first_term)
}

constrMLE_arma <- function(theta, indexes, basisMatrix, first_term) {
    .Call(`_ddfs_constrMLE_arma`, theta, indexes, basisMatrix, first_term)
}

